### ISSUE TITLE
Inconsistent naming choice of application

### ISSUE THREAD

**Issue by ylyma** [ylyma/pe#1]
![image.png](https://raw.githubusercontent.com/ylyma/pe/main/files/80b65426-8248-41ec-a3ec-6152c845f415.png)

![image.png](https://raw.githubusercontent.com/ylyma/pe/main/files/4f267add-acac-4d18-9f9b-250a77ddc51e.png)

Inconsistent naming choice for application. It's called "npc_track" in certain places, but the file is called "npctrack".

**Comment by nus-se-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
This is how we decided to name the file and it is very much preference, AB3 and addressbook.json is one case and it is what we choose to.

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

<catcher-end-of-segment><hr>
