### ISSUE TITLE
Cannot input grades with decimals

### ISSUE THREAD

**Issue by ylyma** [ylyma/pe#9]
![image.png](https://raw.githubusercontent.com/ylyma/pe/main/files/400bee5b-ea0b-4392-aa1c-febcec189d4f.png)

It might be good to say that the score needs to be an integer under the Extra Information section, and update the error message to describe the error better. This is the error message that I got from adding a decimal grade.

![image.png](https://raw.githubusercontent.com/ylyma/pe/main/files/d7ddd242-99f5-474d-af65-ff14aabfaf08.png)

**Comment by nus-pe-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2324S1/pe/master/files/3d9f8984-2ec0-4e31-b375-9956f1c2a912.png)

We did specify in the UG that it needs to be an integer

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

<catcher-end-of-segment><hr>
